
<table class="container table table-striped table-hover">
    <tr>
        <th>Creador</th>
        <th>Nombre del Proyecto</th>
        <th>Ver Proyecto</th>
        <?php
        if(!empty($_SESSION['rol'])){
                if($_SESSION['rol']==1){
            ?>
                    <th>Agregar Participante</th>
                    <th>Editar</th>
                    <th>Eliminar</th>
            <?php
            }
        }
        ?>
    </tr>